### PR TITLE
The git command forwards options and arguments as expected. Closes #8

### LINKED ISSUE #8: pypass wont let me pass options to git

### PR DESCRIPTION
**Pull request by prabi**

### CODE REVIEW

**Comment by aviau** [comment]
Great! Can you think of a test that would verify this?

**Comment by prabi** [comment]
Sure. My favorite is `pypass --PASSWORD_STORE_DIR a_test_vault git log -1 --pretty=%B` which shows the last commit message (and two newlines) in `a_test_vault` if it's a git repo. It works when I use it in the terminal.

On the other hand, when I automate it with `self.run_cli(['git', 'log', '-1', '--pretty=%B'])` I get
```
WARNING: terminal is not fully functional
-  (press RETURN)
```
in the console. I think this is a limitation of `click.testing.CliRunner.invoke`. Do you have any idea how to overcome this?

**Comment by aviau** [comment]
Maybe that is because git log requires a terminal for the scrolling function.

Maybe another command would work?

**Comment by prabi** [comment]
Thank you for your great suggestion. I switched from the previous test case to `git commit --amend -m sth` which works flawlessly. I also used a slightly different implementation straight from click's [advanced documentation](http://click.palletsprojects.com/en/7.x/advanced/).

**Comment by aviau** [comment]
Awesome! Thanks :tada:

**Pull request merged**
